from __future__ import annotations

from threading import Lock
from typing import Any
from uuid import UUID

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.db.session import engine

_TABLE_READY = False
_TABLE_LOCK = Lock()


def ensure_auditor_verifications_table() -> None:
    global _TABLE_READY
    if _TABLE_READY:
        return
    with _TABLE_LOCK:
        if _TABLE_READY:
            return
        with engine.begin() as conn:
            conn.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS auditor_verifications (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        claim_id UUID NOT NULL REFERENCES claims(id) ON DELETE CASCADE,
                        auditor_id VARCHAR(100),
                        auditor_decision VARCHAR(20) NOT NULL,
                        notes TEXT NOT NULL DEFAULT '',
                        confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
                        reviewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                    )
                    """
                )
            )
            conn.execute(
                text(
                    """
                    CREATE INDEX IF NOT EXISTS idx_auditor_verifications_claim_id_reviewed_at
                    ON auditor_verifications (claim_id, reviewed_at DESC)
                    """
                )
            )
        _TABLE_READY = True


def insert_auditor_verification(
    db: Session,
    *,
    claim_id: UUID,
    auditor_id: str | None,
    auditor_decision: str,
    notes: str,
    confidence: float,
) -> dict[str, Any]:
    ensure_auditor_verifications_table()
    row = db.execute(
        text(
            """
            INSERT INTO auditor_verifications (
                claim_id,
                auditor_id,
                auditor_decision,
                notes,
                confidence
            )
            VALUES (
                :claim_id,
                :auditor_id,
                :auditor_decision,
                :notes,
                :confidence
            )
            RETURNING
                id,
                claim_id,
                auditor_id,
                auditor_decision,
                notes,
                confidence,
                reviewed_at
            """
        ),
        {
            "claim_id": str(claim_id),
            "auditor_id": (str(auditor_id).strip()[:100] if auditor_id else None),
            "auditor_decision": str(auditor_decision or "").strip().lower(),
            "notes": str(notes or ""),
            "confidence": float(confidence or 0.0),
        },
    ).mappings().one()
    return dict(row)


def get_latest_auditor_verification(db: Session, *, claim_id: UUID) -> dict[str, Any] | None:
    ensure_auditor_verifications_table()
    row = db.execute(
        text(
            """
            SELECT
                id,
                claim_id,
                auditor_id,
                auditor_decision,
                notes,
                confidence,
                reviewed_at
            FROM auditor_verifications
            WHERE claim_id = :claim_id
            ORDER BY reviewed_at DESC, id DESC
            LIMIT 1
            """
        ),
        {"claim_id": str(claim_id)},
    ).mappings().first()
    return dict(row) if row is not None else None

