from __future__ import annotations

import json
from threading import Lock
from typing import Any
from uuid import UUID

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.db.session import engine

_TABLE_READY = False
_TABLE_LOCK = Lock()


def ensure_doctor_verifications_table() -> None:
    """Create table once per process (avoid DDL on request sessions)."""
    global _TABLE_READY
    if _TABLE_READY:
        return
    with _TABLE_LOCK:
        if _TABLE_READY:
            return
        with engine.begin() as conn:
            conn.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS doctor_verifications (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        claim_id UUID NOT NULL REFERENCES claims(id) ON DELETE CASCADE,
                        doctor_id VARCHAR(100),
                        doctor_decision VARCHAR(20) NOT NULL,
                        notes TEXT NOT NULL DEFAULT '',
                        edited_fields JSONB NOT NULL DEFAULT '{}'::jsonb,
                        verified_data JSONB NOT NULL DEFAULT '{}'::jsonb,
                        checklist_result JSONB NOT NULL DEFAULT '{}'::jsonb,
                        confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
                        reviewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                    )
                    """
                )
            )
            conn.execute(
                text(
                    """
                    CREATE INDEX IF NOT EXISTS idx_doctor_verifications_claim_id_reviewed_at
                    ON doctor_verifications (claim_id, reviewed_at DESC)
                    """
                )
            )
        _TABLE_READY = True


def insert_doctor_verification(
    db: Session,
    *,
    claim_id: UUID,
    doctor_id: str | None,
    doctor_decision: str,
    notes: str,
    edited_fields: dict[str, Any],
    verified_data: dict[str, Any],
    checklist_result: dict[str, Any],
    confidence: float,
) -> dict[str, Any]:
    ensure_doctor_verifications_table()
    row = db.execute(
        text(
            """
            INSERT INTO doctor_verifications (
                claim_id,
                doctor_id,
                doctor_decision,
                notes,
                edited_fields,
                verified_data,
                checklist_result,
                confidence
            )
            VALUES (
                :claim_id,
                :doctor_id,
                :doctor_decision,
                :notes,
                CAST(:edited_fields AS jsonb),
                CAST(:verified_data AS jsonb),
                CAST(:checklist_result AS jsonb),
                :confidence
            )
            RETURNING
                id,
                claim_id,
                doctor_id,
                doctor_decision,
                notes,
                edited_fields,
                verified_data,
                checklist_result,
                confidence,
                reviewed_at
            """
        ),
        {
            "claim_id": str(claim_id),
            "doctor_id": (str(doctor_id).strip()[:100] if doctor_id else None),
            "doctor_decision": str(doctor_decision or "").strip().lower(),
            "notes": str(notes or ""),
            "edited_fields": json.dumps(edited_fields or {}, ensure_ascii=False),
            "verified_data": json.dumps(verified_data or {}, ensure_ascii=False),
            "checklist_result": json.dumps(checklist_result or {}, ensure_ascii=False),
            "confidence": float(confidence or 0.0),
        },
    ).mappings().one()
    return dict(row)


def get_latest_doctor_verification(db: Session, *, claim_id: UUID) -> dict[str, Any] | None:
    ensure_doctor_verifications_table()
    row = db.execute(
        text(
            """
            SELECT
                id,
                claim_id,
                doctor_id,
                doctor_decision,
                notes,
                edited_fields,
                verified_data,
                checklist_result,
                confidence,
                reviewed_at
            FROM doctor_verifications
            WHERE claim_id = :claim_id
            ORDER BY reviewed_at DESC, id DESC
            LIMIT 1
            """
        ),
        {"claim_id": str(claim_id)},
    ).mappings().first()
    return dict(row) if row is not None else None

