from __future__ import annotations

import json
from threading import Lock
from typing import Any
from uuid import UUID

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.db.session import engine

_READY = False
_LOCK = Lock()


def ensure_document_analyses_table() -> None:
    """Create table once per process (avoid DDL inside request sessions)."""
    global _READY
    if _READY:
        return
    with _LOCK:
        if _READY:
            return
        with engine.begin() as conn:
            conn.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS document_analyses (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        index_id UUID NOT NULL REFERENCES document_indexes(id) ON DELETE CASCADE,
                        queries JSONB NOT NULL DEFAULT '[]'::jsonb,
                        top_k_per_query INT NOT NULL DEFAULT 5,
                        use_ai BOOLEAN NOT NULL DEFAULT TRUE,
                        model_name VARCHAR(80),
                        analysis JSONB NOT NULL DEFAULT '{}'::jsonb,
                        created_by VARCHAR(100),
                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                    )
                    """
                )
            )
            conn.execute(
                text(
                    """
                    CREATE INDEX IF NOT EXISTS idx_document_analyses_index_id_created_at
                    ON document_analyses (index_id, created_at DESC)
                    """
                )
            )
        _READY = True


def insert_analysis(
    db: Session,
    *,
    index_id: UUID,
    queries: list[str],
    top_k_per_query: int,
    use_ai: bool,
    model_name: str | None,
    analysis: dict[str, Any],
    created_by: str | None,
) -> dict[str, Any]:
    ensure_document_analyses_table()
    row = db.execute(
        text(
            """
            INSERT INTO document_analyses (
                index_id,
                queries,
                top_k_per_query,
                use_ai,
                model_name,
                analysis,
                created_by
            )
            VALUES (
                :index_id,
                CAST(:queries AS jsonb),
                :top_k_per_query,
                :use_ai,
                :model_name,
                CAST(:analysis AS jsonb),
                :created_by
            )
            RETURNING
                id,
                index_id,
                queries,
                top_k_per_query,
                use_ai,
                model_name,
                analysis,
                created_by,
                created_at
            """
        ),
        {
            "index_id": str(index_id),
            "queries": json.dumps(queries or [], ensure_ascii=False, allow_nan=False),
            "top_k_per_query": int(top_k_per_query or 5),
            "use_ai": bool(use_ai),
            "model_name": (str(model_name).strip()[:80] if model_name else None),
            "analysis": json.dumps(analysis or {}, ensure_ascii=False, allow_nan=False),
            "created_by": (str(created_by).strip()[:100] if created_by else None),
        },
    ).mappings().one()
    return dict(row)


def get_latest_analysis(db: Session, *, index_id: UUID) -> dict[str, Any] | None:
    ensure_document_analyses_table()
    row = db.execute(
        text(
            """
            SELECT
                id,
                index_id,
                queries,
                top_k_per_query,
                use_ai,
                model_name,
                analysis,
                created_by,
                created_at
            FROM document_analyses
            WHERE index_id = :index_id
            ORDER BY created_at DESC, id DESC
            LIMIT 1
            """
        ),
        {"index_id": str(index_id)},
    ).mappings().first()
    return dict(row) if row is not None else None

