export const ROLE_LABELS = {
  super_admin: "Super Admin",
  doctor: "Doctor",
  user: "User",
  auditor: "Auditor",
};

export const NAV = {
  super_admin: [
    { page: "dashboard", label: "Dashboard" },
    { page: "create-user", label: "Create User" },
    { page: "change-password", label: "Change My Password" },
    { page: "reset-user-password", label: "Reset User Password" },
    { page: "bank-details", label: "Bank Details" },
    { page: "payment-sheet", label: "Payment Sheet" },
    { page: "upload-excel", label: "Upload Excel" },
    { page: "claim-rules", label: "Claim Rules" },
    { page: "diagnosis-criteria", label: "Diagnosis Criteria" },
    { page: "rule-suggestions", label: "Rule Suggestions" },
    { page: "medicines", label: "Medicines" },
    { page: "storage-maintenance", label: "Storage Maintenance" },
    { page: "ai-prompt", label: "AI Prompt" },
    { page: "legacy-sync", label: "Legacy Migration" },
  ],
  doctor: [
    { page: "dashboard", label: "Dashboard" },
    { page: "assigned-cases", label: "Assigned Cases" },
    { page: "change-password", label: "Change My Password" },
  ],
  user: [
    { page: "dashboard", label: "Dashboard" },
    { page: "upload-excel", label: "Upload Excel" },
    { page: "assign-cases", label: "Assign Cases" },
    { page: "withdrawn-claims", label: "Withdrawn Claims" },
    { page: "upload-document", label: "Upload Document" },
    { page: "completed-not-uploaded", label: "Completed (Not Uploaded)" },
    { page: "completed-uploaded", label: "Completed (Uploaded)" },
    { page: "export-data", label: "Export Data" },
    { page: "allotment-date-wise", label: "Allotment Date Wise" },
    { page: "change-password", label: "Change My Password" },
  ],
  auditor: [
    { page: "dashboard", label: "Dashboard" },
    { page: "audit-claims", label: "Audit Claims" },
    { page: "change-password", label: "Change My Password" },
  ],
};

export const PAGE_TITLES = {
  dashboard: "Dashboard",
  "create-user": "Create User",
  "change-password": "Change Password",
  "reset-user-password": "Reset User Password",
  "claim-rules": "Claim Rules",
  "diagnosis-criteria": "Diagnosis Criteria",
  "rule-suggestions": "Rule Suggestions",
  medicines: "Medicines",
  "storage-maintenance": "Storage Maintenance",
  "ai-prompt": "AI Prompt",
  "legacy-sync": "Legacy Migration",
  "assigned-cases": "Assigned Cases",
  "case-detail": "Case Detail",
  "upload-excel": "Upload Excel",
  "assign-cases": "Assign Cases",
  "withdrawn-claims": "Withdrawn Claims",
  "upload-document": "Upload Document",
  "completed-not-uploaded": "Completed Reports (Not Uploaded)",
  "completed-uploaded": "Completed Reports (Uploaded)",
  "export-data": "Export Full Data",
  "allotment-date-wise": "Allotment Date Wise",
  "bank-details": "Bank Details",
  "payment-sheet": "Payment Sheet",
  "audit-claims": "Audit Claims",
};

